### ISSUE TITLE
Add EU Cookie Disclaimer

### ISSUE THREAD

**Issue by floriangaerber** [cnvs/canvas#173]
http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm

**Comment by tomschlick** [comment]
Whats the plan for plugins @austintoddj? I would this this would be better suited for a plugin because most people wouldn't need this...

**Comment by Vviizard** [comment]
@tomschlick It applies to any EU-based organisation/legal entity, I wouldn't exactly call that a small amount of people. But I am all :thumbsup: for plugins!

**Comment by austintoddj** [comment]
@Vviizard @tomschlick I agree, this might be best suited in as a plugin. I think the 'ecosystem' of Canvas has to grow a little, and that's why I created the [Palette](https://github.com/austintoddj/palette) repo, to hold the themes. I believe a repo for plugins would be appropriate, but could use some help in how we integrate them into Canvas. So, the biggest hurdles I see for Canvas right now are:

1. An Upgrade process for future versions
2. Plugins to extend the functionality of Canvas
3. Making it so Canvas *could* be added to an existing Laravel app

So, tall order. I'm very open to any and all help you can provide.

**Comment by Jeroen-G** [comment]
[This package could do the trick.](https://github.com/spatie/laravel-cookie-consent)

**Comment by austintoddj** [comment]
Thanks @Jeroen-G! I'll look into this right away.

**Comment by Jeroen-G** [comment]
You want a PR implementing this?

**Comment by austintoddj** [comment]
@Jeroen-G @Vviizard Just thought of something. One way we could include/not-include this feature, since it wouldn't be needed by anyone not in the EU, would be to check the application's timezone. If the application lives in any of the specified EU timezones, then we include the cookie/disclaimer. 

Thoughts?

**Comment by Jeroen-G** [comment]
Or a boolean in the config :)

**Comment by Jeroen-G** [comment]
This can probably also be closed.
