### ISSUE TITLE
Error on adding a post with the same slug

### ISSUE THREAD

**Issue by mabd91** [cnvs/canvas#276]
On creating a post with a slug that already exists a database error occurs, and the entered data is completely lost.

#### To Reproduce: Create a new post with existing slug
<img width="400" alt="Enter data with existing slug" src="https://cloud.githubusercontent.com/assets/10493652/21208951/251d9cce-c27a-11e6-96ae-214f1401d7e2.png">

#### Output: Database unique integrity constraint violation
<img width="400" alt="database error" src="https://cloud.githubusercontent.com/assets/10493652/21208960/2f9b257c-c27a-11e6-8390-5706e397631e.png">

**Comment by austintoddj** [comment]
Thanks for catching this. If you wouldn't mind, could you [submit a new issue](https://github.com/cnvs/easel/issues) over on the Easel repository, since that is where the core code of Canvas lives? Once you create one there with all of this information, you can close this one out and we can address it there.

**Comment by austintoddj** [comment]
Moved the issue to [Easel](https://github.com/cnvs/easel/issues/27).
