### ISSUE TITLE
Tag Page Query Speed

### ISSUE THREAD

**Issue by mabd91** [cnvs/canvas#277]
In cnvs/easel/src/jobs/BlogIndexData.php

Improve query performance by using the Tag's 'id' column instead of the Tag's 'tag' column

```php
$posts = Post::where('published_at', '<=', Carbon::now())
            ->whereHas('tags', function ($q) use ($tag) {
               // $q->where('tag', '=', $tag->tag);
               $q->where('id', '=', $tag->id);
            })
            ->where('is_draft', 0)
            ->orderBy('published_at', $reverse_direction ? 'asc' : 'desc')
            ->simplePaginate(config('blog.posts_per_page'));
```

**Comment by austintoddj** [comment]
Thanks for catching this. If you wouldn't mind, could you [submit a new issue](https://github.com/cnvs/easel/issues) over on the Easel repository, since that is where the core code of Canvas lives? Once you create one there with all of this information, you can close this one out and we can address it there.
