### ISSUE TITLE
'https://github.com/austintoddj/laravel-jsvalidation.git/' not found

### ISSUE THREAD

**Issue by hxor** [cnvs/canvas#285]
What's wrong with this package ?

**Comment by austintoddj** [comment]
@hxor  Right now, Canvas is in the process of transforming into 2 separate repositories, so an issue like this falls under what is to be expected during this process. Apologies for the issue, but it will be resolved in the next available release.

The removal of `austintoddj/laravel-jsvalidation` was fixed by re-adding `proengsoft/laravel-jsvalidation`. v3.0.0 should release in less than a month, if you could hold out till then, Canvas will more than meet your expectations. 👍

**Comment by newpain01** [comment]
Is there any way to install Canvas now? I am getting the same error when I run composer install and I am not able to install it.

**Comment by arekpietrzyk** [comment]
@austintoddj I agree with @newpain01. You should fix this ASAP, because now package looks like broken when first install.

**Comment by austintoddj** [comment]
@arekpietrzyk @newpain01 Thanks for your thoughts on this. If all goes well, hoping to release this week. Keep a watchful eye.. 👁

**Comment by newpain01** [comment]
Let me know if I can help. 
Apart from that, sometimes I get this error: (appeared when I created the first tag, and at few other places)
`BadMethodCallException in Builder.php line 2450:
Call to undefined method Illuminate\Database\Query\Builder::getTablePrefix()`

**Comment by austintoddj** [comment]
Yup good catch @newpain01. That issue will be resolved by the next release and a pretty detailed hunt of that bug can be found [here](https://github.com/cnvs/easel/issues/38).

**Comment by austintoddj** [comment]
Ok @newpain01 @arekpietrzyk , the latest release is out and should solve this issue. Feel free to close it out when you see it work! 👍
