### ISSUE TITLE
Planning on making it a package?

### ISSUE THREAD

**Issue by Naoray** [cnvs/canvas#308]
Hey there,

Do you guys have considered on releasing canvas as a package to integrate in other laravel applications?Guess this would draw even more attention to this repo.

**Comment by austintoddj** [comment]
Since there is a little bit of configuration that needs to happen while integrating the core package (Easel) and Canvas, they will remain as they are for the time being. 

There is however [good documentation here](https://cnvs.readme.io/docs/integrating-canvas-in-an-existing-project) on integrating Canvas into an existing application. It is a bit more advanced, but very possible. Feel free to check it out, give it a try, and see what you think! 👍

**Comment by Naoray** [comment]
@austintoddj thanks for the fast reply. Will try it out soon!
