### ISSUE TITLE
Upload images, request problem

### ISSUE THREAD

**Issue by eresendez** [cnvs/canvas#341]
Maybe it is a simple issue or has already been answered before, sorry but when I want to upload an image I get the following error of request:

**{Files.length: ["The files.length must be a file."], Files.item: ["The files.item must be a file."]}**

I'm uploading a .jpg image, could it be a permissions error?
Btw, excellent platform and I only need to upload images in my posts. 

What can I do?

**Comment by austintoddj** [comment]
Thanks for checking it out @eresendez! @talvbansal Do you have any input on this?

**Comment by talvbansal** [comment]
Hi @eresendez,

It sounds like the issue you're having is likely to be caused by using an older version of Canvas with a newer version of the Media-Manager.

You should upgrade your canvas install or lock the media manager version in your composer.json file to 2.0.2 to fix this issue.

Hope that helps!

**Comment by austintoddj** [comment]
Does what @talvbansal said take care of your issue @eresendez?

**Comment by eleazarbr** [comment]
Hello, sorry for not responding...

My problem was not solved updating to the latest version, I consider that the problem is mine because I use a shared hosting with laravel, I must have some route or a misconfigured permission.

At localhost I have no problem. 

The issue may be closed, however I will continue to do more testing :smiley:
