### ISSUE TITLE
Upgrade from 3.3 to 3.4 theme issue

### ISSUE THREAD

**Issue by blueyama** [cnvs/canvas#351]
When upgrading from 3.3 to 3.4 I ran into the issue with the default paper theme still using `JsValidator` in places see here (line 15): https://github.com/cnvs/paper/blob/master/resources/views/auth/login.blade.php I was using a custom theme I forked from the default paper theme, but when I went to the source I see the latest commit is still using it. To get around this I referenced the dark paper theme and was able to get it working, so its just an FYI. 

Btw thanks for building this repo so far I'm really liking it and looking forward to what goodies might be coming out with the 5.4 release.

**Comment by austintoddj** [comment]
Thanks for the kind words @blueyama! The themes have undergone a bit of changing since you last forked, and JSValidator was one of the items that got removed due to an upgrade issue with the package. [Here](https://cnvs.readme.io/docs/changelog#section-removed) is the changelog entry. 

And you're right to keep your eye out for the next release, it'll take care of a number of bugs and bring the app up to speed with Laravel 5.4 👍

**Comment by blueyama** [comment]
I'm keeping an eye out for the next release 💯 
 
Ah indeed, I missed the fact that the `cnvs/easel` repo had the paper theme views prepackaged with it. I guess this would only effect the people who have forked from the paper theme. I'm guessing the two repos should be even:
https://github.com/cnvs/paper/blob/master/resources/views/auth/login.blade.php
https://github.com/cnvs/easel/blob/master/resources/views/auth/login.blade.php

**Comment by austintoddj** [comment]
Yes you're right they should be even. Organizing and refactoring the themes is another task for the next release so we don't run into these issues anymore.
