### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by nielvrom** [cnvs/canvas#356]
When I run the application locally I don't have any problems logging in. But when I place the application online at [https://blog.mydomainname.be](https://blog.mydomainname.be) than I'm having problems to login. The HTTPS certificate is provided through Cloudflare (also Automatic HTTPS Rewrites). 

In my **console** I see this warning:

> Mixed Content: The page at 'https://blog.mydomainname.be/admin' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://blog.mydomainname.be/auth/login'. This endpoint should be made available over a secure connection.

I'm not getting any errors logging in. The page just refreshes.

**Comment by unrivaledcreations** [comment]
Check your `config/app.php` file. There should be a line there that reads, `'url' => 'https://blog.mydomainname.be'`. Make sure that says 'https' and not 'http'.

**Comment by nielvrom** [comment]
Still the same, the action of my form is still `http://blog.mydomainname.be/auth/login`. When I change that manually (with inspect element) to https it works.

**Comment by glennmcewan** [comment]
A little late to the party, but hopefully this will help you out...

The URL in `config/app.php` will have no effect, as if you read the docblock, it explains that it is used in the **console**, not in a web request.

The URL scheme used when calling the `route` helper is extrapolated from the current request's scheme. However, there is one gotcha...

The reason this is failing is actually a Laravel + Cloudflare SSL issue rather than Canvas. See this Stackoverflow Answer explaining the issue:
https://stackoverflow.com/questions/24426423/laravel-generate-secure-https-url-from-route/35076800#35076800

It boils down to a method in the Symfony HTTPFoundation repo:
https://github.com/symfony/http-foundation/blob/master/Request.php#L1093

Because Cloudflare is not a 'trusted proxy', it will be marked as non-secure.

Do a little bit of Googling about setting up Laravel with Cloudflare SSL and you'll find plenty of solutions, but basically if you're certain you want to serve all routes via HTTPS -- which it looks like you do -- then you'll most likely want to create a new Middleware class to set the list of trusted proxies.

**Comment by austintoddj** [comment]
Thanks @glennmcewan for the insight. 👍
