### ISSUE TITLE
Where are all the files?

### ISSUE THREAD

**Issue by JakariaAmin** [cnvs/canvas#376]
Forgive me for being stupid but where are all the files like resources>view or http>controllers, database>migrations.

I have followed the instructions provided and crated the project, everything working fine canvas blog but can't find any controller or view files to modify.
There are some files in the tests>integrations though.

**Comment by davidsivocha** [comment]
@JakariaAmin Canvas the application has a dependency on cnvs/easel which is what contains the core package. You'll find it [here](https://github.com/cnvs/easel).

It's worth noting that because it's been developed as package you won't find he same structure as a laravel package. 

If you're looking for the files on your local install, you'd find them in `/vendor/cnvs/easel`

**Comment by davidsivocha** [comment]
Worth mentioning as well that you can run `php artisan vendor:publish` to copy the views at least into your local resources folder

**Comment by austintoddj** [comment]
@davidsivocha is correct. Thanks for jumping in.
