### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dtovar** [cnvs/canvas#451]
I try so many times to install via composer and using xampp, maybe i'm a idiot. Where can i find a live demo?

**Comment by austintoddj** [comment]
What sort of errors are you running into?

**Comment by dtovar** [comment]
Hi!
I have installed xampp and then I have executed the following command in the console:
composer create-project --prefer-dist cnvs/canvas blog
the route has been c: \ xampp \ htdocs

Then this:
php artisan canvas:install
the route has been c: \xampp\htdocs\blog

Error:
Could not open input file: artisan
It may be obvious, I do not know if I am doing the whole process as it should. I have tried creating a new project and installing laravel and I can execute artisan command.

**Comment by austintoddj** [comment]
First off, you won't be able to create a project with `composer create-project cnvs/canvas` since it's not a full Laravel installation. The error is popping up because the Artisan console is a feature of Laravel, which looks like it hasn't been installed yet. 

Canvas is a package that integrates with a Laravel application, so you'll need to have an existing project that you want to use it in. [Check this out](https://laravel.com/docs/5.8) for getting a new instance of Laravel up and running.

Once you've got Laravel installed, follow the [installation steps](https://github.com/cnvs/canvas#installation) to integrate Canvas.
