### ISSUE TITLE
Unit Tests fail for missing Service Provider

### ISSUE THREAD

**Issue by austintoddj** [cnvs/canvas#456]
The unit tests utilize [orchestral/testbench](https://github.com/orchestral/testbench).

The latest build on `master` passes, with 2 ignored failure exceptions which can be seen [here](https://travis-ci.org/cnvs/canvas/builds/517909351). 

To reproduce the current error, run the following:

```sh
# Clone the repo
git clone https://github.com/cnvs/canvas

# Install the dependencies
composer install

# Run the tests
composer test
```

You should see the following error:
```
Error: Class 'App\Providers\CanvasServiceProvider' not found
```

I'm not sure where this error is coming from, or why it's just now starting to pop up. As far as I know, the app shouldn't be looking in the `App\Providers` namespace since the package service provider is overridden in the `getPackageProviders()` method in the TestCase.

Any help on this is greatly appreciated.

**Comment by talvbansal** [comment]
The reason this is failing is because the `App\Providers\CanvasServiceProvider` class doesn't exist as you've identified. 

What looks to be happening is that the `App\Providers\CanvasServiceProvider` and the `Canvas\CanvasServiceProvider` from the `getPackageProviders` method are both attempting to be registered with the first one causing the failure:

```php
....
  20 => "Illuminate\Validation\ValidationServiceProvider"
  21 => "Illuminate\View\ViewServiceProvider"
  22 => "App\Providers\CanvasServiceProvider"
  23 => "Canvas\CanvasServiceProvider"
]
```

According to the docs `getPackageProviders` doesn't replace anything it just adds in any extra service providers. So in this case i think whats happening is the expected the behaviour.

The problem comes with the first test of `install_assets_and_configuration`. 
If you do the following:

- Add `$this->markTestSkipped();` to `install_assets_and_configuration`
- delete the vendor folder
- run `composer install`
- run `composer test`

Then the tests work properly. It seems that part of the `canvas:install` command generates a config file that makes reference to  `App\Providers\CanvasServiceProvider` and at the end of the test that config file is not cleaned up. So for all subsequent tests the above reference is being looked for.

All tests should be idempotent so the world is scaffolded freshly on each test. I believe removing the config file `./vendor/orchestra/testbench-core/laravel/config/app.php` at the end of the `install_assets_and_configuration` tests will fix the problems.

**Comment by austintoddj** [comment]
Thanks for looking at that @talvbansal. I just found this as well which led me to try using the `tearDown()` method to clear the app, but perhaps it's only clearing the app when all the tests have run: [https://github.com/orchestral/testbench/issues/173](https://github.com/orchestral/testbench/issues/173). If I still can't get get it working with `tearDown()`, I might just skip testing this command altogether, since it's not extremely useful to test.

**Comment by talvbansal** [comment]
Yeah looking into this some more there doesn't seem to be a quick way to reset the whole app folder between tests `vendor/orchestra/testbench-core/laravel/` weird as i'd imagine that'd have been pretty normal but for the short term maybe just mark the console tests as skipped until a proper fix is found.
