### ISSUE TITLE
Question: Any interest in this PR for Posts/Page Export?

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#516]
@austintoddj This is not an issue by any means, and I don't much care for this particular feature myself, but sharing if there's any interest in integrating this into cnvs
https://github.com/writingink/wink/issues/188
Package: https://github.com/WyattCast44/winkexport

**Comment by austintoddj** [comment]
I did have this in mind a couple months ago, since I've seen a nice implementation of it on Medium itself. 

The decision I arrived at however is that there really isn't a need for an export function, since downloading your data is a feature normally found on platforms where you don't actually own your data. Since Canvas is managed by the developer/owner of the blog itself, they can already do whatever they want to their data (ie. export). 

Thanks for the find though!
