### ISSUE TITLE
GET http://localhost/vendor/canvas/js/app.js 404 (Not Found)

### ISSUE THREAD

**Issue by alxzhdanov** [cnvs/canvas#535]
I create new blank project on latest version of laravel. Install Canvas. Frontend work fine.
But when I try to create new post I get partly rendered form and error in console.
How I can solve this problem?

**Comment by austintoddj** [comment]
What is the error in the console?

**Comment by alxzhdanov** [comment]
yes
`PS C:\Program Files (x86)\VertrigoServ\www\canvas2> php artisan canvas:install
Installation complete.`

**Comment by austintoddj** [comment]
Interesting. I'm curious as to why the CSS is loading correctly and the JS in the same vendor directory would fail to load. Could you try to force publish the assets one more time and let me know the outcome?

```
php artisan canvas:publish --force
```

**Comment by alxzhdanov** [comment]
No effect. Same error.

**Comment by austintoddj** [comment]
The frontend working fine makes sense, as those files are stubbed out during the setup command. It seems like something happened during the installation process that prevented those files from being copied over.

Could you try running a fresh install one more time and let me know if:

1. Anything in the logs shows up
2. The `/public/vendor/canvas` directory exists after running the install command

**Comment by bishopm** [comment]
I have the same issue. Nothing to see in the logs and the /public/vendor/canvas directory does exist.

I can work around by changing line 42 in the app.blade.php layout file from

`<script type="text/javascript" src="{{ mix('js/app.js', 'vendor/canvas') }}"></script>`

to 

`<script type="text/javascript" src="http://localhost/blog/public/vendor/canvas/js/app.js?id=69daa38e45d3d953f71e"></script>`

ie: mix('js/app.js', 'vendor/canvas') is generating the wrong path (localhost/vendor instead of localhost/blog/public/vendor)

The stylesheet url is correct in the layout, but the shortcut icon link also is wrong (/vendor/canvas/favicon.ico?id=dbb0c05daa3432643753). I don't know much about Laravel Mix but the issue seems to be there, right?

**Comment by austintoddj** [comment]
I'm still unable to replicate this error.

If the `vendor/canvas` directory exists, there shouldn't be a reason why you'd need to modify the path. Plus, the stylesheet URL is loading correctly but not the favicon?

Any further details you can provide would be helpful. I'd like to get this sorted and make this work for you but just haven't been able to reproduce it.

**Comment by fmuiin14** [comment]
> No effect. Same error.
> 
> I move file from http://localhost/vendor/cnvs/canvas/public/js/app.js
> to this path http://localhost/vendor/canvas/js/app.js
> 
> And it's work fine. But I think this is not good :)

I do this, but I just found another problem. 

![Screenshot_10](https://user-images.githubusercontent.com/17643540/82736827-90c80f80-9d56-11ea-9d4b-e46e6186e017.png)


And when I do php artisan canvas:publish, I just back to first error js and css not found
