### ISSUE TITLE
Potential roadmap for Cnvs?

### ISSUE THREAD

**Issue by connecteev** [cnvs/canvas#539]
Hi @austintoddj long time no chat...I see you've been busy on cnvs' "spa" branch. Out of curiosity:
1. is the "spa" branch going to be just for the admin section of cnvs, or does it include the front-end also? Having a SPA for the front-end makes sense, for the admin section less so (unless you're doing it purely for the technical challenge of learning vue)
2. Any plans you are able to share on the open issues / functionality I had previously logged and/or requested? It's perfectly fine to say we won't be doing one or more of them anytime soon, but some sort of expectation would be great. I am just curious because I want to find a path to get that functionality available.

Again, thanks for cnvs!

**Comment by austintoddj** [comment]
Sure thing.

The `spa` branch is my main focus, and like you keenly observed, it's mainly for the technical challenge of getting a deeper understanding of Vue. Since none of the issues in the tracker are reproducible bugs at the moment, they will be addressed as soon as I'm able to merge this branch in. It's 85% there, just some things to clean up and implement.

Thanks for keeping an eye on the repo, I am still planning on tackling the issues once this is wrapped up, my intent is that it'll be shipped next month. Hope that gives you some hope!

**Comment by connecteev** [comment]
@austintoddj makes sense, and Vue / Vuex / VueRouter is a great piece of tech to learn. I'm also considering Nuxt for my front-end so I can get SSR out of the box....but I still love Laravel.

Look forward to that 15% of the ```spa``` being done so that we can get to some juicy features. By the way, I'll let you "close" this one once you've read it....and I have some fresh ideas for you this morning...will comment and/or log separately.
