### ISSUE TITLE
SEO Doubts

### ISSUE THREAD

**Issue by albertoelias123** [cnvs/canvas#627]
Hello, I would like to understand how the SEO of Canvas Post's works.

- Is a Site-Map generated?
- The automatically generated slug for posts, is not a friendly url, would it be more interesting to generate a slug from the title?
- Do you have any future plans to improve SEO?

**Comment by austintoddj** [comment]
There is no sitemap generated for you. Might be a good thing to add in the future. 

The auto-generated slugs are meant to add ambiguity to each post, so that whenever you create content it's guaranteed to not interfere with other posts  you've already created. It may not be a bad idea to implement a "sync" feature to the slug field that allows users to 1-click generate a slug based on the post title, similar to what the SEO Settings part does:

<img width="487" alt="Screen Shot 2020-02-10 at 1 44 32 PM" src="https://user-images.githubusercontent.com/8037011/74184099-c31c8980-4c0b-11ea-9632-abebc5b3afd4.png">

Other than that, I don't have any SEO-related items that I'm working on. If you have any specific ideas that you want to see added, feel free to open an Issue or PR for it!

**Comment by s72817** [comment]
+1 for sitemap :)
