### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by robertgarrigos** [cnvs/canvas#641]
I'm translating Canvas in to Catalan, but I'm having some problems with missing strings. I saw that the lang/en directory has only two translations files now (just update from a previous version). I translated those two files, then, but then the views are still pulling strings from missing translations files, like pagination.php, or stats.php. Some of these string are within in the new file app.php, but some are missing.

Is there something I've done wrong during the upgrade process or is it really that the localization is not working right now?

**Comment by austintoddj** [comment]
There is a refactor that's going to do away with the `blog.php` lang file, so we'll only be left with one file per translation. It's currently on the `develop` branch at the moment, so feel free to [take a look here](https://github.com/cnvs/canvas/blob/develop/resources/lang/en/app.php) and see what the final will look like.

**Comment by robertgarrigos** [comment]
I realized that I needed to put the lang files within the vendor/cnvs/canvas directory. Would'nt be better to publish the lang files in the resources directory? This way, anyone wishing to adjust or add a translation would find it easier. Having to add files within the vendor directory, which is ignored by git, is not comfortable.

In any case, there are still some missing strings only in the frontend (pagination and 'you might enjoy').

**Comment by austintoddj** [comment]
If translations were published to your `resources` directory, then any upgrade path going forward would become more difficult. 

So what you did was correct by submitting the PR, since that'll get your preferred translation into the project and you'll never have to add something to the `vendor` directory.

As far as the frontend translations, that'll be taken care of by an upcoming release.
