### ISSUE TITLE
User-specific tags and toipcs

### ISSUE THREAD

**Issue by vimalmistry** [cnvs/canvas#727]
I am working on my personal blog since feb. I already installed version "5.0". But I just now I installed latest version of canvas. 
I found Tags and Topic are inserted user wise. Can you explain? Why?

![Screenshot 2020-04-25 at 12 22 28 PM](https://user-images.githubusercontent.com/3993163/80273463-d231b480-86ef-11ea-9b89-95dac7c3a474.png)
![Screenshot 2020-04-25 at 12 22 19 PM](https://user-images.githubusercontent.com/3993163/80273465-d3fb7800-86ef-11ea-9fa8-549df92291c0.png)

**Comment by austintoddj** [comment]
Absolutely. They are user-specific so that if you make a post and tag it with a few things, another user can't come in and delete those tags, thus affecting your content. This keeps things separate just in case you plan to have multiple users. If you don't, you won't notice a difference and you can keep publishing content however you choose.

**Comment by vimalmistry** [comment]
Strange feature I can say. It also make conflict on fetch posts by topic and categories. We are not making multiple blog for individual user. So topic and tags should be same for all users. at least my requirement is like this.

**Comment by austintoddj** [comment]
If this continues to be a point of frustration for other developers as well, I'll look into making adjustments to it. I appreciate the feedback!
